type Query {
	continents: [Continent!]!
	continent(code: String!): Continent
	countries(filter: FilterCountryInput): [Country!]!
	country(code: String!): Country
	languages: [Language!]!
	language(code: String!): Language
}

type Continent {
	code: String!
	name: String!
	countries(filter: FilterCountryInput): [Country!]!
}

input FilterCountryInput {
	limit: Int
	offset: Int
}

type Country {
	code: String!
	name: String!
	native: String
	phone: [String!]
	continent: Continent!
	currency: [String!]
	languages: [Language!]
	emoji: String
	subdivisions: [Subdivision!]
}

"""
Сущность языка
Присутствуют почти все языки для стран
"""
type Language {
	"Уникальный код языка"
	code: String!
	name: String!
	native: String!
	rtl: Boolean!
	countries: [Country!]! # TODO: добавить фильтр - FilterCountryInput
}

type Subdivision {
	code: String!
	type: String! @deprecated(reason: "Перестали поддерживать")
	name: String!
}
